---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.a51a5ce4-4a25-43da-b3be-ab314825f174

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.49a5724a-7386-4cab-9c76-0d251d446c57.Boolean.Property
        operator: ne
        operands:
            - "false"
