---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.59bb6edc-b0c9-4dde-969d-6ef3b76fa01e

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.6d2e6e66-b38c-4b42-bc97-1374ccd0d5f6.Boolean.Property
        operator: ne
        operands:
            - "false"
