---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.695ee477-325a-4885-b32c-33ab0e9ac8bf

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.706ddfde-15df-4935-ba5b-8b4b11d033f6.Boolean.Property
        operator: ne
        operands:
            - "false"
