---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.4dfa7e95-bddc-4cc2-8d50-63622e157a9b

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.43a15895-e568-403d-8c05-13c8d5dd32a0.Boolean.Property
        operator: ne
        operands:
            - "false"
