---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.764a40de-06f1-4235-bb96-99c65a73a571

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.5955b254-1b2f-4d10-a75a-4d558e3c0da5.Boolean.Property
        operator: ne
        operands:
            - "false"
