---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.65a84e58-d40d-4f45-b9dc-220edf2d191c

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.38d3eaea-0cc8-41c6-af5f-266439eb317e.Boolean.Property
        operator: ne
        operands:
            - "false"
