---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.d697b6c9-0628-4aa6-b255-51f46c84e0af

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.bd807e65-cd67-4f1f-ba24-30bd12d1d600.Boolean.Property
        operator: ne
        operands:
            - "false"
