---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.c83062ee-5065-4d9c-9006-437b50b1c14d

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.f67f4860-174c-4d8a-84d2-cdab4072f0a3.Boolean.Property
        operator: ne
        operands:
            - "false"
