---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.86dc4d47-583f-4bb0-b6c6-5ec2df69fcf2

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.ae0d7200-addd-4a4f-99e0-7ef176aff565.Boolean.Property
        operator: ne
        operands:
            - "false"
