---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.61b32455-1163-445d-921f-ddc25b3ab638

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.0832f93c-37ba-4343-98f7-cfff7fd4853f.Boolean.Property
        operator: ne
        operands:
            - "false"
