---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.c7a5c4d5-fbaf-44fe-84fc-f7ed5c243b23

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.ebdd7cc9-cd92-4665-85b1-be1281605a9f.Boolean.Property
        operator: ne
        operands:
            - "false"
