---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: Target-group.19b31a5f-1c18-4a91-a14c-f86218b030ea

description: Target group 1

conditions:
  allOf:
    - property:
        name: Boolean.a4d4e545-94a5-4857-acc1-04e16e815f94
        operator: ne
        operands:
            - "false"
