---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: Target-group.f113aba5-7309-497f-8b65-4febff15bd90

description: Target group 1

conditions:
  allOf:
    - property:
        name: Boolean.3726cf9e-960c-4e8a-9da3-039e0d0ee471
        operator: ne
        operands:
            - "false"
