---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: Target-group.b492b274-0e89-47f0-95fd-3d018a3d9476

description: Target group 1

conditions:
  allOf:
    - property:
        name: Boolean.de67fe87-1d41-462f-b2a1-798f82270ef5
        operator: ne
        operands:
            - "false"
