---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: tg-1

description: 

conditions:
  allOf:
    - property:
        name: userEmail
        operator: in-array
        operands:
            - "321"
