---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: sdk-key-test-flag
flagType: boolean
description: Updated the desc
labels:

availableValues:
  - "true"
  - "false"

isPermanent: false
